### ISSUE TITLE
Talp example bug: doesn't print the summary table.

### ISSUE THREAD

**Issue by TovRudyy** [bsc-pm/dlb#1]
When executing the talp exampe located in dlb/doc/examples/talp it does not print the table summary with the profiling information at the end of its execution. 

The reason of that is because the source file talp_01.c lacks one MPI_Finalize() call before the DLB_Finalize():

```
int main(int argc, char *argv[])
{
.
.
.
    } else {
        printf("DLB failed with the following error: %s\n", DLB_Strerror(err));
    }
    printf("Finalizing TALP example.\n");
    MPI_Finalize();
    DLB_Finalize();

    return 0;
}
```
All the best,

**Comment by vlopezh** [comment]
Fixed in 57de413
Thanks Olek
