### ISSUE TITLE
test failure

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [bsc-pm/dlb#2]
I've packaged dlb for the gentoo overlay guru but our CI failed at testing it
https://bugs.gentoo.org/784698

Build log: https://784698.bugs.gentoo.org/attachment.cgi?id=701454

**Comment by vlopezh** [comment]
DLB tests are performed using the static libraries. Remove `--disable-static` from the configure line and they should work.

**Comment by Alessandro-Barbieri** [comment]
thanks
